package hello;

public class Config {
    String jsonString = "[{\"left_table\":{\"database\":\"datalake\",\"name\":\"dim_campaign\",\"columns\":[\"id\",\"label\",\"client_id\",\"campaign_id\"],\"sort_columns\":[\"id\",\"label\",\"client_id\",\"campaign_id\"],\"generate_unique_id\":false,\"generate_sort_id\":false,\"filter\":[]},\"right_table\":{\"database\":\"datalake\",\"name\":\"dim_aimconfigs_campaign\",\"columns\":[\"id\",\"label\",\"client_id\",\"campaign_id\",\"process_date\"],\"sort_columns\":[\"id\",\"label\",\"client_id\",\"campaign_id\"],\"generate_unique_id\":false,\"generate_sort_id\":false,\"filter\":[]},\"join\":{\"method\":\"FULL\",\"on\":[[\"id\",\"id\",\"EQUAL\"]],\"sort_join\":false,\"unique_join\":false},\"compare\":[[\"label\",\"label\",\"NOT_EQUAL\"],[\"client_id\",\"client_id\",\"NOT_EQUAL\"],[\"campaign_id\",\"campaign_id\",\"NOT_EQUAL\"]]},{\"left_table\":{\"database\":\"datalake\",\"name\":\"dim_partner_deactivation\",\"columns\":[\"partner_deactivation_id\",\"record_created_ts\",\"partner_name\",\"effective_from_ts\",\"effective_to_ts\"],\"sort_columns\":[\"partner_deactivation_id\",\"record_created_ts\",\"partner_name\",\"effective_from_ts\",\"effective_to_ts\"],\"generate_unique_id\":false,\"generate_sort_id\":false,\"filter\":[]},\"right_table\":{\"database\":\"datalake\",\"name\":\"dim_aimconfigs_partner_deactivation\",\"columns\":[\"partner_deactivation_id\",\"record_created_ts\",\"partner_name\",\"effective_from_ts\",\"effective_to_ts\",\"process_date\"],\"sort_columns\":[\"partner_deactivation_id\",\"record_created_ts\",\"partner_name\",\"effective_from_ts\",\"effective_to_ts\"],\"generate_unique_id\":false,\"generate_sort_id\":false,\"filter\":[]},\"join\":{\"method\":\"FULL\",\"on\":[[\"partner_deactivation_id\",\"partner_deactivation_id\",\"EQUAL\"]],\"sort_join\":false,\"unique_join\":false},\"validate_unique\":true,\"compare\":[[\"record_created_ts\",\"record_created_ts\",\"NOT_EQUAL\"],[\"partner_name\",\"partner_name\",\"NOT_EQUAL\"],[\"effective_from_ts\",\"effective_from_ts\",\"NOT_EQUAL\"],[\"effective_to_ts\",\"effective_to_ts\",\"NOT_EQUAL\"]]}]";

    String input = "[{\"left_table\":{\"database\":\"datalake\",\"name\":\"dim_partner_deactivation\",\"columns\":[\"partner_deactivation_id\",\"record_created_ts\",\"partner_name\",\"effective_from_ts\",\"effective_to_ts\"],\"sort_columns\":[\"partner_deactivation_id\",\"record_created_ts\",\"partner_name\",\"effective_from_ts\",\"effective_to_ts\"],\"generate_unique_id\":false,\"generate_sort_id\":false,\"filter\":[]},\"right_table\":{\"database\":\"datalake\",\"name\":\"dim_aimconfigs_partner_deactivation\",\"columns\":[\"partner_deactivation_id\",\"record_created_ts\",\"partner_name\",\"effective_from_ts\",\"effective_to_ts\",\"process_date\"],\"sort_columns\":[\"partner_deactivation_id\",\"record_created_ts\",\"partner_name\",\"effective_from_ts\",\"effective_to_ts\"],\"generate_unique_id\":false,\"generate_sort_id\":false,\"filter\":[]},\"join\":{\"method\":\"FULL\",\"on\":[[\"partner_deactivation_id\",\"partner_deactivation_id\",\"EQUAL\"]],\"sort_join\":false,\"unique_join\":false},\"validate_unique\":true,\"compare\":[[\"record_created_ts\",\"record_created_ts\",\"NOT_EQUAL\"],[\"partner_name\",\"partner_name\",\"NOT_EQUAL\"],[\"effective_from_ts\",\"effective_from_ts\",\"NOT_EQUAL\"],[\"effective_to_ts\",\"effective_to_ts\",\"NOT_EQUAL\"]]}]";


}
